### ISSUE TITLE
Human readable cast names

### ISSUE THREAD

**Issue by jimhlad** [vkovic/laravel-custom-casts#10]
I think it would be awesome to be able to specify the cast name in human readable format:

```
protected $casts = [
    'amount' => MoneyCast::class
];
```

becomes

```
protected $casts = [
    'amount' => 'money'
];
```

Perhaps the approach used could be similar to how Laravel infers the policy class names using the `guessPolicyNamesUsing` method.

How difficult would this be to add? Not super familiar with this package yet so wasn't sure how much effort is involved (although happy to help out as well!)

**Comment by vkovic** [comment]
Neat little feature I agree. It should not be hard, I'll take a look into it as soon as I have some time available.

Perhaps If you have time, take a look into the code, it's pretty simple, self explaining and there is just couple of files. You could suggest or even write a solution and if you need help I'll be glad to 
give you a hand.

**Comment by vkovic** [comment]
Just looked into the PR - i don't like the idea that it only works if custom cast classes are in `App/Casts` namespace.

I just took a look into default Laravel way of casting attributes and it can't be applied to this package since Laravel knows all of its cast types in advance and we don't.

As a potential solution I suggest doing this via config that can be published (using service provider) if user wants to use this feature. 

Config file might look something like:

```php
// File: config/custom-casts.php

return [
    'amount' => MoneyCast::class,
    'image' => ImageCast::class,
];
```

**Comment by jimhlad** [comment]
@vkovic I thought about using the config file approach as well. It will work for sure. 

Wondering if there's a hybrid approach though. I was trying for a more "convention over configuration" solution mimicking how Laravel handles the auto-discovery of Policy classes using the `guessPolicyNamesUsing` method. It assumes the `app/Policies` directory, but this can be explicitly overridden by doing something like:

```php
// File: app/Providers/AuthServiceProvider.php
use Illuminate\Support\Facades\Gate;

Gate::guessPolicyNamesUsing(function ($modelClass) {
    // return policy class name...
});
```
Or in the case of this package, by extending the trait before using it in your model:

```php
// File: app/Traits/MyHasCustomCasts.php
trait MyHasCustomCasts
{
    use HasCustomCasts;

    protected function guessCastClassName($identifier)
    {
        // Override default namespace for finding the cast classes
    }
}

// File: app/Models/MyModel.php
class MyModel extends Model
{
    use MyHasCustomCasts;
}
```
It's possible I'm misunderstanding why this approach wouldn't work as I'm not that familiar with how casts are handled in the Laravel core. I was mostly just curious if there's a way to avoid defining another array. Like how accessors just kind of work magically.

**Comment by vkovic** [comment]
The approach you suggested would work for sure, but it would introduce unnecessary complexity into the package.

I think the way with publishing config would be sufficient, balanced and easy to implement.

If you're interested to help with that, I, and of course the community would be grateful  🥇 😄

**Comment by jimhlad** [comment]
@vkovic I modified the PR to switch it over to a config file implementation.

Let me know what you think. Please feel free to jump in if you see something that looks like it can be improved :)

Note: I have not yet tested the config publishing logic.

**Comment by vkovic** [comment]
I just made some progress, but there is some more things to be done.

@jimhlad plese check `feature/cast-type-alias`, i merged your changes, made some improvements and write simple test.

Still we need to write documentation (in `README.md`) and to maybe create some more tests.
I stil did not test it on laravel instalation, just on local project and php-unit tests

**Comment by vkovic** [comment]
@jimhlad Finally i found some time to improve tests and make them understandable.
Everything is on the `feature/cast-type-alias` branch.

If you have time, maybe you can just test everything with Laravel installation.
You should: 
1. manually register service provider (`config/app.php`)
2. publish config
3. assign some custom cast to any model 
4. try it out

🍺 🍺

**Comment by vkovic** [comment]
Everything is tested and working. It's now available on the master branch.

Checkout `README.md` for more info.
