### ISSUE TITLE
FirstOrCreate issue

### ISSUE THREAD

**Issue by gareth-ib** [vkovic/laravel-custom-casts#13]
**Describe the bug**

Running
```php
$email = Network\Email::firstOrCreate( $emailParams );
```
also tried
```php
$email = new Network\Email;
$email->firstOrCreate( $emailParams );
```
Those don't run the data conversion.
Although running...
```php
$email = Network\Email::create( $emailParams );
```
Does run the conversion just fine.

**To Reproduce**
My cast class is
```php
class PostgresArray extends CustomCastBase
{
    public function setAttribute($value)  {
        if (is_string($value))  return $value;
        if (is_array($value))   return "{" . implode(',', $value) . "}";
    }
    public function castAttribute($value)   {
        if (is_string($value))  return $value;
        if (is_array($value))   return "{" . implode(',', $value) . "}";
    }
}
```

I'm on the latest current version of your library, using Laravel 6.

I had added ```dd``` commands in my cast to make sure it wasn't executing.

Am I missing something from my cast or is this a limitation with the library?

Thanks!

**Comment by vkovic** [comment]
@gareth-ib Thanks for the bug report, I'll test this today.

**Comment by vkovic** [comment]
Ok, i just do a quick test and it seems fine. 

Can you elaborate, I'm not sure what is your custom cast field on the `Email` model and what are the `$emailParams`.

**Comment by gareth-ib** [comment]
oh here...

```php
use App\CustomCasts\PostgresArray;
class Email extends \Illuminate\Database\Eloquent\Model
{
    use \Vkovic\LaravelCustomCasts\HasCustomCasts;
	protected $casts = [
	    'visitor_ids' => PostgresArray::class,
	];
}
```
and...
```php
$emailParams = [
    'visitor_ids' => [1,2,3,4]
];
```
then...
```php
$email = Network\Email::firstOrCreate( $emailParams );
```

**Comment by vkovic** [comment]
Ok, i will make assumption based on your code, so we may continue from there.

When you say:

```php
$email->firstOrCreate( $emailParams );
```
I suppose you can do something like:

```php
$emailParams = [
    // ...
    'visitor_ids' => [1,2,3,4],
    // ...
];
$email = Network\Email::firstOrCreate( $emailParams );

if($email->visitor_ids == [1,2,3,4]) {
    echo "everything is ok";
};
```

There are two things here 
1. I'm not sure what are you doing afterwards, are you accessing model field `visitor_ids` like i did or differently
2. based on our case, a new model will always be created because it will try to query database against unserialized data (array in this case) - in other words it'll actually compare it with db value of `"{1,2,3,4}"` which is never the case

**Comment by gareth-ib** [comment]
well it breaks trying to do the query... like this

```php
$emailParams = [
    'visitor_ids' => [2581,180134],
];
$email = Network\Email::firstOrCreate( $emailParams );
```
or
```php
$email = Network\Email::where( $emailParams )->first();
```
those both give the error
```bash
Illuminate\Database\QueryException  : 
SQLSTATE[HY093]: 
Invalid parameter number: parameter was not defined 
(SQL: select * from "network"."email" where ("visitor_ids" = 2581) limit 1)
```
So the translation of the values isn't happening on the part where it queries the database...

But if I do
```php
$emailParams = [
    'visitor_ids' => [2581,180134],
];
$email = Network\Email::create( $emailParams );
```
it perfectly compiles the array into the postgres array format and inserts it into the database. That make sense? It's literally just not casting the value on the `select` part of the process, but it is fine on the insert part.

the table being...
```sql
CREATE TABLE network.email (
	email_id serial NOT NULL,
	visitor_ids int4[] NOT NULL,
	PRIMARY KEY (email_id)
);
```

**Comment by vkovic** [comment]
I just took a look at the possible problem and found that Laravel itself has the same issue. I did not have enough time to investigate, but this should be it: https://github.com/laravel/framework/issues/25773. 

If this is still unsolved by the Laravel community, I prefer to leave it as is, and than when it's implemented we could adapt to their logic.

@gareth-ib Can you perhaps investigate a bit on your side, so we can confirm that my proposition is valid.

**Comment by gareth-ib** [comment]
yeah that ticket seems to be the reason... weird they haven't fixed it after so long. I commented on there, I'll keep looking into it

**Comment by vkovic** [comment]
I'll close this issue now, but feel free to resubmit after that Laravel issue is solved. 

Thanks for your time @gareth-ib 🍻
