### ISSUE TITLE
Manager

### ISSUE THREAD

**Issue by Marko298** [vkovic/laravel-custom-casts#19]
To give people to distribute their custom casts, we have to add the ability to dynamically register new casts. In laravel such functionality is done using `Manager::class` and `extend` method. 

```php 
class PackageServiceProvider extends ServiceProvider
{
    public function register()
    {        
        $this->app->make(CustomCastManager::class)->extend('file', FileCast::class);
    }
}

```

**Comment by vkovic** [comment]
Can you elaborate - as I understood we should give people possibility to write their own casts and to be able to distribute it for other users of the package - is this correct?

I have never used `Manager::class` directly, so currently I'm unaware of its exact functionality.

**Comment by Marko298** [comment]
Exactly, you can take look at how DatabaseManager works. For example, you can add custom drivers in order to support MongoDB.

**Comment by vkovic** [comment]
I didn't look into `Manager:class` functionality yet, and before that just want to clear some things out. 

Wouldn't the easy way to use community distributed custom casts would be just to include certain class from corresponding repository - in other words, one could find `AwesomeCast` in `acme/laravel-awesome-cast` package and include it in his own project like:

```php
use Acme\LaravelAwesomeCast\AwesomeCast;

class Product extends Model
{
    use HasCustomCasts;

    protected $casts = [
        'some_column' => AwesomeCast::class
    ];
}
```

**Comment by Marko298** [comment]
You can do this just by using FQDN, but it would be cool if I can register cast alias in package, so users can just use `protected $casts = ['some_column' => 'file'];`.
Also with parameters, it would be even better  `protected $casts = ['some_column' => 'file:disk,path'];`.

**Comment by Marko298** [comment]
I want to support all methods at a time: FQDN, config, extend via the service provider

**Comment by vkovic** [comment]
I agree that this would be awesome, but we might have naming collisions problem.

Also, when the package config is published, we can just bind external classes, using FQCN, like:

```php
// File: config/custom_casts.php

return [
    'awesome_cast' => Acme\LaravelAwesomeCast\AwesomeCast::class
];
```

**Comment by Marko298** [comment]
With Manager we can throw Exception on name collision. Also, package developer can add in their config disable bool:

```php
// File: config/some_package_config.php

return [
    'register_custom_casts_aliases' => true,
];

```

```php
// File: src/SomePackageServiceProvider.php

class SomePackageServiceProvider extends ServiceProvider
{
    public function register()
    {
        if (config('some_package_config.register_custom_casts_aliases')) {
            $this->app->make(CustomCastManager::class)
                      ->extend('cast1', Cast1::class)
                      ->extend('cast2', Cast2::class)
                      ->extend('cast3', Cast3::class);
        }
    }
}

```

**Comment by vkovic** [comment]
I'm closing this issue for now since lack of interest / time
