### ISSUE TITLE
Inserts null values when attribute is not present

### ISSUE THREAD

**Issue by realprabs** [vkovic/laravel-custom-casts#5]
When the attribute is not present in a create/update call, null is inserted. This causes issues with non nullable columns with default values.

**Comment by vkovic** [comment]
Hi, thanks for the info... Can hou maybe write a test for this and I'll act upon. If you need additional info  I can help

**Comment by realprabs** [comment]
Looks like this behaviour was added explicitly in this commit: https://github.com/vkovic/laravel-custom-casts/commit/94783a2271ddbd6c90189904d68202b5e0422e05

May I know what was the reason?

**Comment by realprabs** [comment]
To reproduce it in test, just make the image field non nullable in migration.

```php
Schema::create('images', function (Blueprint $table) {
            $table->increments('id');
            $table->text('image')->default('default.png');
            $table->text('data')->default('[]');

            $table->timestamps();
});
```
Test will throw
```
1) Vkovic\LaravelCustomCasts\Test\Integration\ModelCanUseCustomCastsTest::it_can_handle_unset_attribute
Illuminate\Database\QueryException: SQLSTATE[23000]: Integrity constraint violation: 19 NOT NULL constraint failed: images.image (SQL: insert into "images" ("data", "image", "updated_at", "created_at") values ([], ?, 2019-07-05 07:30:22, 2019-07-05 07:30:22))
```

**Comment by vkovic** [comment]
To be able to explain why we implemented https://github.com/vkovic/laravel-custom-casts/commit/94783a2271ddbd6c90189904d68202b5e0422e05, consider this code:

```php
use Vkovic\LaravelCustomCasts\Test\Support\Models\Image;

$newImage = Image::create();

dump($newImage->image); // null

$newImage->refresh();
        
dump($newImage->image); // 'placeholder.png'
```

Later dump gives us correct value, while first is wrong. This is because custom cast field (`image` in this case) is not set until we call `Model::refresh()`.

Considering problematics, it is better to have documentation (until I or someone else figure out better way) saying that if yo want to use custom casts on newly created model, you need to call `Model::refresh`.

I will revert changes from mentioned commit and update README.md

**Comment by vkovic** [comment]
@jaysson I just committed the changes. Please check if everything is ok now. I need to reorganize tests a bit, but I don't have time currently, so I would like to know is it working on your side, where it failed previously?

**Comment by realprabs** [comment]
> This is because custom cast field (image in this case) is not set until we call Model::refresh().

That is true for regular eloquent attributes as well. I would suggest not handling it until there is a change in Eloquent (if at all). https://github.com/laravel/framework/issues/21449

The change should work, I will try it tomorrow.

**Comment by vkovic** [comment]
>  I would suggest not handling it until there is a change in Eloquent (if at all)not be handled 

I totally agree. 

I'm closing issue right now - suppose everything is fine now.
