### ISSUE TITLE
Lumen compatibility

### ISSUE THREAD

**Issue by silwerclaw** [vkovic/laravel-custom-casts#6]
According to your composer you are strictly targeting Laravel framework, however inside you are using only it's components like eloquent and maybe it's dependencies. 

All the functionality can be easily reused inside Lumen framework (micro-framework of Laravel) cause it also has support for Eloquent usage.  But unfortunately your composer requires from me specially Laravel. 

Pls change your dependencies to concrete illuminate packages versions so this package can be installed on both Laravel and Lumen

**Comment by vkovic** [comment]
Hi @silwerclaw, thanks for the info. I'll look into this in a couple of days.

**Comment by vkovic** [comment]
@silwerclaw can you try running:

`composer require vkovic/laravel-custom-casts:dev-master`

I just did some changes - it should work, but since I never used **Lumen**, maybe you can help me check everything works as expected.
